# File generated by Flopy version 3.9.3 on 10/22/2025 at 19:28:25.
BEGIN attributes
  NAMES  s_1_23_41  s_1_24_41  s_1_25_40  s_1_26_40  s_1_27_39  s_1_28_39  s_1_29_39  s_1_30_38  s_1_31_38  s_1_32_38  s_1_33_37  s_1_34_37  s_1_35_38  s_1_36_38  s_1_37_38  s_1_38_38  s_1_39_38  s_1_40_39  s_1_41_39  s_1_42_39  s_1_43_39  s_1_44_39  s_1_45_39  s_1_46_38  s_1_46_39
END attributes

BEGIN timeseries
    OPEN/CLOSE  'local_run1.ghb_pw_heads.csv'
END timeseries

