# File generated by Flopy version 3.9.3 on 11/01/2025 at 07:08:44.
BEGIN attributes
  NAMES  s_1_33_31  s_1_34_31  s_1_34_32  s_1_34_33  s_1_34_34  s_1_35_31  s_1_35_32  s_1_35_34  s_1_36_34  s_1_37_33  s_1_37_34  s_1_38_33
END attributes

BEGIN timeseries
    OPEN/CLOSE  'local_run9.ghb_spring_heads.csv'
END timeseries

