# File generated by Flopy version 3.9.3 on 09/10/2025 at 14:31:45.
BEGIN attributes
  NAMES  s_1_28_34  s_1_29_34  s_1_29_35  s_1_29_36  s_1_29_37  s_1_30_34  s_1_30_35  s_1_30_37  s_1_31_37  s_1_32_36  s_1_32_37  s_1_33_36
END attributes

BEGIN timeseries
    OPEN/CLOSE  'local2.spring_stage.csv'
END timeseries

