# File generated by Flopy version 3.9.3 on 09/10/2025 at 14:31:45.
BEGIN attributes
  NAMES  h_1_18_44  h_1_19_44  h_1_20_43  h_1_21_43  h_1_22_42  h_1_23_42  h_1_24_42  h_1_25_41  h_1_26_41  h_1_27_41  h_1_28_40  h_1_29_40  h_1_30_41  h_1_31_41  h_1_32_41  h_1_33_41  h_1_34_41  h_1_35_42  h_1_36_42  h_1_37_42  h_1_38_42  h_1_39_42  h_1_40_42  h_1_41_42  h_1_42_42  h_1_43_42  h_1_44_42  h_1_45_42  h_1_46_42  h_1_47_42  h_1_48_42  h_1_49_41  h_1_50_41
END attributes

BEGIN timeseries
    OPEN/CLOSE  'local2.ghb_pw_heads.csv'
END timeseries

