# File generated by Flopy version 3.9.3 on 09/02/2025 at 13:49:46.
BEGIN attributes
  NAMES  s_1_68_82  s_1_69_82  s_1_69_88  s_1_69_89  s_1_70_83  s_1_70_87  s_1_70_90  s_1_71_83  s_1_71_84  s_1_71_85  s_1_71_86  s_1_71_90  s_1_72_91  s_1_73_91  s_1_74_91  s_1_75_91  s_1_76_89  s_1_76_90  s_1_77_88  s_1_78_88  s_1_79_88  s_1_80_87
END attributes

BEGIN timeseries
    OPEN/CLOSE  'local2.spring_stage.csv'
END timeseries

