# File generated by Flopy version 3.9.3 on 09/03/2025 at 16:47:55.
BEGIN attributes
  NAMES  s_1_14_18  s_1_15_18  s_1_15_19  s_1_16_19  s_1_17_19
END attributes

BEGIN timeseries
    OPEN/CLOSE  'local2.spring_stage.csv'
END timeseries

