# File generated by Flopy version 3.9.3 on 09/03/2025 at 16:47:55.
BEGIN attributes
  NAMES  h_1_10_23  h_1_11_22  h_1_12_22  h_1_13_21  h_1_14_21  h_1_15_21  h_1_16_21  h_1_17_21  h_1_18_22  h_1_19_22  h_1_20_22  h_1_21_22  h_1_22_22  h_1_23_22  h_1_24_22  h_1_25_21
END attributes

BEGIN timeseries
    OPEN/CLOSE  'local2.ghb_pw_heads.csv'
END timeseries

