# File generated by Flopy version 3.9.3 on 09/11/2025 at 10:54:54.
BEGIN attributes
  NAMES  h_1_23_41  h_1_24_41  h_1_25_40  h_1_26_40  h_1_27_39  h_1_28_39  h_1_29_39  h_1_30_38  h_1_31_38  h_1_32_38  h_1_33_37  h_1_34_37  h_1_35_38  h_1_36_38  h_1_37_38  h_1_38_38  h_1_39_38  h_1_40_39  h_1_41_39  h_1_42_39  h_1_43_39  h_1_44_39  h_1_45_39  h_1_46_38  h_1_46_39
END attributes

BEGIN timeseries
    OPEN/CLOSE  'local2.ghb_pw_heads.csv'
END timeseries

